version: '3.8'

services:
  mediator:
    image: rodopincha/didcomm-mediator
    ports:
      - '8000:8000'
    environment:
      - DB_URL=mongodb://db
      - PUBLIC_URL=https://mediator.rootsid.cloud
      - ROTATE_OOB=0
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:

